require(RMySQL)

con <- dbConnect(MySQL(), username = "saaspass", password = "saaspass", host = "192.168.10.252", dbname = "saaspass") # konektiranje na host...
lista <- dbGetQuery(conn = con ,statement = "select * from companies")                                                # primer za query...
dbDisconnect(conn = con)                                                                                              # Disconect from the database...

str(dbGetQuery(conn = con,"select * from public_services"))
